// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD57rCL4kc16YcpbtUd7Oyr3yEG2dQ6S1Q',
    appId: '1:279412183478:web:1a6f8bb365dccc7c397117',
    messagingSenderId: '279412183478',
    projectId: 'myapp-b50b6',
    authDomain: 'myapp-b50b6.firebaseapp.com',
    storageBucket: 'myapp-b50b6.appspot.com',
    measurementId: 'G-S1NH082TJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPFdURd-2p3Tcfu8318iugJgOENiwHspM',
    appId: '1:279412183478:android:056bb4b9a8b4c8b5397117',
    messagingSenderId: '279412183478',
    projectId: 'myapp-b50b6',
    storageBucket: 'myapp-b50b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-dOVUnu-R9_YAQs6axmWAYROMNed-lQ',
    appId: '1:279412183478:ios:f9f90c56781af20b397117',
    messagingSenderId: '279412183478',
    projectId: 'myapp-b50b6',
    storageBucket: 'myapp-b50b6.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-dOVUnu-R9_YAQs6axmWAYROMNed-lQ',
    appId: '1:279412183478:ios:4d54e0eb09118c9e397117',
    messagingSenderId: '279412183478',
    projectId: 'myapp-b50b6',
    storageBucket: 'myapp-b50b6.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
